language: c++

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libopenmpi-dev
    - sudo apt-get install -qq libhdf5-serial-dev
    - sudo apt-get install -qq cmake

script:
    - |
        mkdir build
        cd build
        cmake ..
        make
        make test
